version: '3.8'

services:
  orders.web:
    image: orders.web
    build:
      context: .
      dockerfile: src/Orders.Web/Dockerfile
    ports:
      - "8081:80"
    networks:
      - kafka

networks:
  kafka:
    external: true
